FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o server .

FROM scratch
COPY --from=build /app/server /server
ENV GODEBUG=gctrace=1
ENV GOMAXPROCS=4
EXPOSE 8080
ENTRYPOINT ["/server"]
