spring:
  application:
    name: scale-experiment
  threads:
    virtual:
      enabled: false
  main:
    banner-mode: off
    lazy-initialization: true
  jmx:
    enabled: false

server:
  port: 8080
  http2:
    enabled: false
  compression:
    enabled: false
  undertow:
    threads:
      io: 24
      worker: 48
    buffer-size: 16384
    direct-buffers: true
  shutdown: immediate

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  metrics:
    enable:
      http: false
      jvm: false
      system: false
      process: false
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: WARN
    com.paulograbin.scale: INFO
